---
- name: Configuración de máquinas virtuales
  hosts: servidores
  become: yes

  tasks:
    - name: Actualizar paquetes
      apt:
        update_cache: yes

    - name: Instalar PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Instalar Git
      apt:
        name: git
        state: present
