- name: RASI backend provisioning
  hosts: all
  remote_user: ansible
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name:
          - git
          - python3
          - python3-pip
        state: latest
        update_cache: yes
        autoclean: yes
        autoremove: yes
      become: yes

    - name: Update permissions for /home/pabluchenko4000/ directory while creating it
      file:
          path: /home/pabluchenko4000/repo
          state: directory
          recurse: yes
          owner: pabluchenko4000
          group: pabluchenko4000
          mode: 0755

    -   name: Clone a github repository
        git:
            repo: https://github.com/Ctrl-AltDefeat/RASI.git
            dest: /home/pabluchenko4000/repo
            clone: yes
            update: yes

