- name: RASI backend provisioning
  hosts: all
  remote_user: ansible
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name:
          - git
          - python3
          - python3-pip
        state: latest
        update_cache: yes
        autoclean: yes
        autoremove: yes
      become: yes

    -   name: Clone a github repository
        git:
            repo: https://github.com/Ctrl-AltDefeat/RASI.git
            dest: /home/pabluchenko4000/RASI
            clone: yes
            update: yes

