---
name: backend CI

on: [push, pull_request, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.1.1
            - uses: actions/setup-python@v4.7.1
              with:
                  cache: "pip"
                  cache-dependency-path: "backend/production_requirements.txt"
            - name: Install dependencies
              run: sudo apt install build-essential python3-dev libpq-dev
            - name: Install python dependencies
              run: |
                  python -m pip install -U pip wheel setuptools
                  python -m pip install -r backend/production_requirements.txt
            - name: Lint with Ruff
              run: |
                  python -m pip install -U ruff
                  ruff --output-format=github .
              continue-on-error: true
